### ISSUE TITLE
Android Proguard

### ISSUE THREAD

**Issue by kenticus** [cloudinary/cloudinary_android#12]
Cloundinary will crash when trying to use proguard to obfuscate the code.

java.lang.UnknownError: Can't find Cloudinary platform adapter [com.cloudinary.android.UploaderStrategy,com.cloudinary.http42.UploaderStrategy,com.cloudinary.http43.UploaderStrategy]

**Comment by kenticus** [comment]
please add this to your proguard file example:
-keep class com.cloudinary.** { *; }

**Comment by madhurtewani-wow** [comment]
For me Cloudinary is crashing with this error even without proguard. Any solution?

**Comment by roeeba** [comment]
Hi @madhurtewani-wow, @kenticus. We apologize for the very delayed response. As it probably not relevant anymore, we're closing this issue. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket, if our assistance is still needed.

**Comment by kayvannj** [comment]
Hey @roeeba,

Proguard for Android is a big issue and I spend some time trying to see if you provide any specific rules for it but was not able to find any. The solution provided by @kenticus is not a solution because it basically disables proguard on cloudinary package all together. 

A well-defined proguard rule would greatly be appreciated.

**Comment by roeeba** [comment]
Hi @kayvannj. This single Proguard rule should be enough:
`-keep class com.cloudinary.android.*Strategy`
