### ISSUE TITLE
Not yet implemented Exception using api().resources()

### ISSUE THREAD

**Issue by kkho** [cloudinary/cloudinary_android#16]
I get an exception calling this method:

Map response = cloudinary.api().resources(ObjectUtils.emptyMap());

**Comment by VihaanVerma89** [comment]
I'm getting the same issue.
http://stackoverflow.com/questions/33505888/cloudinary-list-all-images-not-implemented-exception

Not able to figure out how to get all images json from cloudinary for the 3rd day now :\

**Comment by nadavofi** [comment]
Since Android is a client-side environment and the Admin-API is designated to serve on the server-side, its methods are not implemented for native Android.
You can build the HTTP request on your own, using the ADMIN-API endpoint, and issue it in order to collect the information you require, as described int our docs: http://cloudinary.com/documentation/admin_api

**Comment by VihaanVerma89** [comment]
Hi Nadavofi, 

I get the response on executing 
curl 'https://API_KEY:API_SECRET@api.cloudinary.com/v1_1/CLOUD_NAME/resources/image'

but when I send http GET request to the same url using HttpURLConnection instance I get 401. I'm not adding any other headers to the request. Do I need to add anything else to get list of images on android ?

**Comment by VihaanVerma89** [comment]
Setting below headers in HttpUrlConnection solved my problem.    
        final String basicAuth = "Basic " + Base64.encodeToString("API_KEY:API_SECRET".getBytes(), Base64.NO_WRAP);

            connection.setRequestProperty("Authorization", basicAuth);

**Comment by nadavofi** [comment]
It's strongly unadvisable to have your API-SECRET stored on the Android device (client-side) as it makes it available to unauthorized persons.
Please open a support ticket, and describe your use-case so we can help you find a better way to achieve it.

**Comment by nadavofi** [comment]
I'm marking this issue as closed due to the time elapsed.
If there are any additional questions on that matter, please don't hesitate to contact us via support ticket or open a new Git issue through our current Android repo: https://github.com/cloudinary/cloudinary_java/tree/master/cloudinary-android
