### ISSUE TITLE
401 When trying uploadLarge() file with size more than max chunk size, on uploading second part.

### ISSUE THREAD

**Issue by chopikboy** [cloudinary/cloudinary_android#18]
401 When trying uploadLarge() file with size more than max chunk size, on uploading second part. RuntimeException : Server returned unexpected status code - 401 - {"error":{"message":"Invalid Signature b67b4d901dde99a4375e574d541e355d2e2e077b. String to sign - 'public_id=dropzone-signed-upload/cacya6j0bxwdazdwux9x&timestamp=1453395719&upload_preset=dropzone-signed-upload'."}}

**Comment by TalLevAmi** [comment]
Solved in master of cloudinary_java. Please see if it works for you?

**Comment by chopikboy** [comment]
Did you update jars?

**Comment by roeeba** [comment]
Hi @chopikboy. We apologize for the very delayed response. While it's probably not relevant anymore, a fix was already deployed to Maven central. 
We're closing this issue due to the time elapsed. Please feel free to either re-open the issue, contact our support at http://support.cloudinary.com or create a new ticket if you have any additional issues.
